In [1]:
import numpy as np
from sklearn.datasets import fetch_california_housing

In [2]:
housing = fetch_california_housing(as_frame=True)

In [3]:
housing_df = housing.frame

In [4]:
housing_df.keys()

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude', 'MedHouseVal'],
      dtype='object')

In [5]:
target_col_name = "MedHouseVal"

In [8]:
X = housing_df.drop(columns=target_col_name)

In [9]:
y = housing_df[target_col_name]

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
lr = LinearRegression()

In [12]:
lr.fit(X, y)

LinearRegression()

In [13]:
print(f"Model coefficients (first 5): {lr.coef_[:5]}")

Model coefficients (first 5): [ 4.36693293e-01  9.43577803e-03 -1.07322041e-01  6.45065694e-01
 -3.97638942e-06]

In [15]:
pred = lr.predict(X)

In [16]:
housing_df["pred"] = pred

In [17]:
housing_df.keys()

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude', 'MedHouseVal', 'pred'],
      dtype='object')

In [21]:
housing_df[["MedHouseVal", "pred"]].sample(5)

       MedHouseVal      pred
10997        1.604  2.028742
36           1.045  1.395047
12183        1.146  0.975546
2083         0.584  1.094342
13661        1.237  1.970914

In [22]:
housing_df["diff"] = housing_df["MedHouseVal"] - housing_df["pred"]
housing_df[["MedHouseVal", "pred","diff"]].sample(5)

       MedHouseVal      pred      diff
974          2.385  1.778509  0.606491
19546        0.738  1.081489 -0.343489
9104         1.357  1.754868 -0.397868
2824         1.076  1.368906 -0.292906
9743         2.275  2.630736 -0.355736

In [25]:
# avarage diff
average_diff = housing_df["diff"].sum() / housing_df.shape[0]
average_diff

np.float64(-7.843510509475835e-15)

In [29]:
# Mean Abs Error

In [ ]:
housing_df["abs_diff"] = abs(housing_df["MedHouseVal"] - housing_df["pred"])
housing_df[["MedHouseVal", "pred","diff", "abs_diff"]].sample(5)

In [27]:
av_abs_diff = housing_df["abs_diff"].sum() / housing_df.shape[0]
av_abs_diff

np.float64(0.5311643817546473)

In [34]:
from sklearn.metrics import mean_absolute_error
mean_abs_err = mean_absolute_error(housing_df[target_col_name], housing_df["pred"])
mean_abs_err

0.5311643817546473

In [35]:
av_abs_diff - mean_abs_err

np.float64(0.0)

In [31]:
# mean Square Error

In [32]:
housing_df["square_diff"] = (housing_df[target_col_name] - housing_df["pred"]) ** 2
housing_df[["MedHouseVal", "pred","diff", "abs_diff", "square_diff"]].sample(5)

       MedHouseVal      pred      diff  abs_diff  square_diff
15398        2.946  1.887544  1.058456  1.058456     1.120329
13190        1.292  1.956837 -0.664837  0.664837     0.442009
547          2.208  2.214742 -0.006742  0.006742     0.000045
16150        3.372  2.499134  0.872866  0.872866     0.761895
8063         4.442  3.327315  1.114685  1.114685     1.242524

In [33]:
av_square_diff = housing_df["square_diff"].sum() / housing_df.shape[0]
av_square_diff

np.float64(0.5243209861846072)

In [36]:
from sklearn.metrics import mean_squared_error
mean_square_err = mean_squared_error(housing_df[target_col_name], housing_df["pred"])
mean_square_err

0.5243209861846072

In [37]:
av_square_diff - mean_square_err

np.float64(0.0)

In [ ]:
# Root out of squared mean err

In [40]:
import numpy as np

In [41]:
housing_df["root_square_diff"] = np.sqrt((housing_df[target_col_name] - housing_df["pred"]) ** 2)
housing_df[["MedHouseVal", "pred","diff", "abs_diff", "square_diff", "root_square_diff"]].sample(5)

,MedHouseVal,pred,diff,abs_diff,square_diff,root_square_diff
5437,4.466,3.424064,1.041936,1.041936,1.085630,1.041936
209,1.133,1.345990,-0.212990,0.212990,0.045365,0.212990
19000,1.401,1.907039,-0.506039,0.506039,0.256075,0.506039
14603,1.778,1.710544,0.067456,0.067456,0.004550,0.067456
3666,1.583,1.485376,0.097624,0.097624,0.009530,0.097624

In [42]:
av_root_square_diff = housing_df["root_square_diff"].sum() / housing_df.shape[0]
av_root_square_diff

np.float64(0.5311643817546473)

In [43]:
from sklearn.metrics import root_mean_squared_error
root_mean_square_err = root_mean_squared_error(housing_df[target_col_name], housing_df["pred"])
root_mean_square_err

0.7241001216576387

In [44]:
np.sqrt(mean_square_err)

np.float64(0.7241001216576387)

 R^2 = 1 - \frac { \sum_{i=1}^{n} ( y_i - \hat{y}_i )^2 }
    {\sum_{i=1}^{n} (y_i - \bar{y})^2 }

The Coefficient of Determination, $R^2$, is calculated as:

$$R^2 = 1 - \frac{\sum_{i=1}^{n} (y_i - \hat{y}_i)^2}{\sum_{i=1}^{n} (y_i - \bar{y})^2}$$

In [45]:
1 - (housing_df[target_col_name] - housing_df["pred"]) ** 2 / (housing_df[target_col_name] - housing_df[target_col_name].mean()) ** 2

0        0.974249
1        0.933312
2        0.988527
3        0.983747
4        0.444867
           ...
20635    0.747223
20636    0.971910
20637    0.569363
20638    0.813248
20639    0.896322
Length: 20640, dtype: float64

In [46]:
from sklearn.metrics import r2_score

In [48]:
r_squared = r2_score(housing_df[target_col_name], housing_df["pred"])
r_squared

0.606232685199805

In [49]:
r_squared_by_lr = lr.score(X, y)
r_squared_by_lr

0.606232685199805

In [50]:
# Counting manually

In [54]:
housing_df["const"] = housing_df[target_col_name].sum() / housing_df.shape[0]
housing_df[[target_col_name, "const"]]

       MedHouseVal     const
0            4.526  2.068558
1            3.585  2.068558
2            3.521  2.068558
3            3.413  2.068558
4            3.422  2.068558
...            ...       ...
20635        0.781  2.068558
20636        0.771  2.068558
20637        0.923  2.068558
20638        0.847  2.068558
20639        0.894  2.068558

[20640 rows x 2 columns]

In [55]:
mse_const = mean_squared_error(housing_df[target_col_name], housing_df["const"])
mse_const # like a dispersion

1.3315503000818076

In [56]:
mse_model = mean_squared_error(housing_df[target_col_name], housing_df["pred"])
mse_model

0.5243209861846072

In [57]:
1 - mse_const / mse_model

-1.5395708643502295